POST http://localhost:8080/events
content-type: application/json

{
    "name": "Aula de Programação Competitiva",
    "description": "Uma aula de programação competitiva com um programador do Google",
    "location": "Google meet",
    "dateTime": "2025-03-08T15:30:00.000Z"
}
