DELETE http://localhost:8080/events/5
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InplY2FAZ21haWwuY29tIiwiZXhwIjoxNzQwMzM4NDI0LCJ1c2VySWQiOjN9.1419KaBaM-jUt99z448FVl1a-MEx3xjZg8VLnVBeTjY