POST http://localhost:8080/events/1/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpa2FwYXVAZ21haWwuY29tIiwiZXhwIjoxNzQwMzQ0MzE2LCJ1c2VySWQiOjJ9.4CRr2WM1A3IH3_ymzWoLYRt63b46OFjIkeLSolZBDeM