PUT http://localhost:8080/events/5
content-type: application/json
authorization: put the user token here

{
    "name": "update test",
    "description": "update test",
    "location": "anywhere",
    "dateTime": "2025-03-08T15:30:00.000Z"
}
